export const metadata = {
  title: 'Next. js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Convertin | Conversor de imágenes</title>
        <link rel="icon" href="/icono.ico" />
      </head>
      <body>{children}</body>
    </html>
  )
}